name: Weather Agent

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Inštalácia knižníc
        run: pip install requests openpyxl PyGithub

      - name: Spusti agenta
        working-directory: /home/runner/work/AgentWeather
        env:
          GITHUB_TOKEN: ${{ secrets.WEATHER_TOKEN }}
          GITHUB_USER: slavo1976
        run: python weather_agent.py
